/* Plugin generated by AMXX-Studio */
/*
Falta agregar Huds.
posible multiplicador por banderas?

*/

#include <amxmisc>
#include <superheromod>

#define PLUGIN "Happy Hour y Xp x2"
#define VERSION "1.0"
#define AUTHOR "Lucas"

//Esta es para el que compra admin
#define DATA_FLAG "o"

// Estas es para el que compra multiplicador
#define DATA_FLAG2 "n" 

//new const horas[] = { 15,16,17,18,19,20,21,22,23,00,01,02,03,04,05,06,07,08,09,10 }   // el original no tocar por las dudas
new const horas[] = { 11,12,13,22,23,00,01,02,03,04,05,06,07,08,09,10 } // Esto dice desde las 22:00 hasta las 14:00 Happy Hour
new bool: g_happyhour
new beneficio, beneficioxpadm, beneficioxpx4
new gPcvarXP, HappyHudSync	//, gPcvarXP2, 

public plugin_init()  
{ 
	// Plugin Info
	register_plugin(PLUGIN, VERSION, AUTHOR)
	
	// Comandos
	register_clcmd("say /happy", "verhappy");
	register_clcmd("say /hh", "verhappy");
	register_clcmd("say /multiplicador", "vermultiplicador");
	register_clcmd("say /multiplicadorxp", "vermultiplicador");
	register_clcmd("say /multixp", "vermultiplicador");
	
	//Evento del Happy Hour
	register_event("HLTV", "RoundStart", "a", "1=0", "2=0");
    
	// Cvar Multiplicador del Happy Hour
	beneficio = register_cvar("amx_bonusxp", "2.0");
	// Cvar Multiplicador del Compra Admin
	beneficioxpadm = register_cvar("amx_bonusxpadm", "3.0");
	// Cvar Multiplicador del que compra Multiplicador
	beneficioxpx4 = register_cvar("amx_bonusxpx4", "4.0");
	
	// Ty Jelle for This Code - Es para dar Xp random durante el Happy Hour
	new loopTime = register_cvar("randomxp_time", "210")	//tiempo para dar la xp (en segundos)
	gPcvarXP = register_cvar("randomxp_xptoadd", "1024")	//cantidad de xp que da en Happy Hour
	// gPcvarXP2 = register_cvar("randomxp_xptoadd2", "512")	//cantidad de xp que da si no hay HappyHour
	
	set_task(get_pcvar_float(loopTime), "randomxp_loop", _, _, _, "b")
	
	HappyHudSync = CreateHudSyncObj()
} 
//----------------------------------------------------------------------------------------------
public verhappy(id)
	sh_chat_message(id, -1, "Estamos en HappyHour: O%s", g_happyhour ? "N" : "FF")

public sh_client_spawn(id)
{
	if ( g_happyhour && is_user_alive(id) ) {
		set_hudmessage(0, 128, 0, -0.01, 0.10, 0, 0.0, 10.0, 0.0, 0.0, 4)
		ShowSyncHudMsg(id, HappyHudSync, "HAY HAPPY HOUR! Ganas más XP!!^nPone /multixp para ver tu multiplicador.")
	}
}
//----------------------------------------------------------------------------------------------
public vermultiplicador(id)
{
	if (!g_happyhour) return;
	
	if (has_flag(id, DATA_FLAG)) {	
		sh_chat_message(id, -1, "Tenes un Multiplicador de XP x3 ahora mismo.")
		}
	else if (has_flag(id, DATA_FLAG2)) {	
		sh_chat_message(id, -1, "Tenes un Multiplicador de XP x4 ahora mismo.")
		}
	else 	{	
		sh_chat_message(id, -1, "Tenes un Multiplicador de XP x2 ahora mismo.")
	}
}    
//---------------------------------------------------------------------------------------------- 
public sh_client_death(victim, attacker)
{
	// codigo sacado del copperhead
	new maxplayers = sh_maxplayers();
	if( victim < 1 || victim > maxplayers || attacker < 1 || attacker > maxplayers || victim == attacker ) return;
		
	new level = sh_get_user_lvl(attacker)
	
	if(g_happyhour && is_user_alive(attacker) && victim != attacker ) {
		//prueba para dar multiplicador de xp adm
		if ( has_flag(attacker, DATA_FLAG) || level <= 13 ) {	
			new killxp = sh_get_user_xp(attacker);
			sh_add_kill_xp(attacker, victim, -1.0)
			killxp -= sh_get_user_xp(attacker);	
		
			new parm[2];
			parm[0] = attacker;
			parm[1] = killxp;
			giveXP2(parm);
		}
		//prueba para dar multiplicador de xp		
		else if ( has_flag(attacker, DATA_FLAG2) ) {	
			new killxp = sh_get_user_xp(attacker);
			sh_add_kill_xp(attacker, victim, -1.0)
			killxp -= sh_get_user_xp(attacker);	
			
			new parm[2];
			parm[0] = attacker;
			parm[1] = killxp;
			giveXP3(parm);
		}

		else 	{
			new killxp = sh_get_user_xp(attacker);
			sh_add_kill_xp(attacker, victim, -1.0)
			killxp -= sh_get_user_xp(attacker);	
			
			new parm[2];
			parm[0] = attacker;
			parm[1] = killxp;
			giveXP(parm);
		}
	}
}
//para le happy hour todo ok (o sea para todos)
giveXP(parm[])
{
	new Float:xp_multiplier;
	xp_multiplier = get_pcvar_float( beneficio );
	new xp_outcome = floatround( parm[1] * xp_multiplier );
	
	if(xp_outcome > 0) {
		sh_set_user_xp( parm[0], xp_outcome, true );
	}
}

// para el multiplicador del admin
giveXP2(parm[])
{
	new Float:xp_multiplier;
	xp_multiplier = get_pcvar_float( beneficioxpadm );
	new xp_outcome = floatround( parm[1] * xp_multiplier );
	
	if(xp_outcome > 0) {
		sh_set_user_xp( parm[0], xp_outcome, true );
	}
}
// para el multiplicador de todos
giveXP3(parm[])
{
	new Float:xp_multiplier;
	xp_multiplier = get_pcvar_float( beneficioxpx4 );
	new xp_outcome = floatround( parm[1] * xp_multiplier );
	
	if(xp_outcome > 0) {
		sh_set_user_xp( parm[0], xp_outcome, true );
	}
}
//----------------------------------------------------------------------------------------------
public RoundStart()
{
	new data[12] 
	get_time("%H", data, 12) 
	new Tiempo = str_to_num(data) 
    
	for(new i=0;i <= sizeof horas - 1;i++) { 
		if(Tiempo != horas[i]) continue 
		g_happyhour = true 
		break; 
	} 
    
	/* if(g_happyhour) { 
		// Este es para todos
		sh_chat_message(0, -1, "Estamos en HappyHour, Toda tu XP por Kills se Multiplicará x2, x3 o x4 !!")
	} */
} 
//----------------------------------------------------------------------------------------------
public randomxp_loop()
{
	if (!sh_is_active()) return
	
	new players[32], playerCount
	get_players(players, playerCount, "h")
	 
	if (playerCount > 0) {
		new player, name[32], iXPtoAdd
		player = players[random(playerCount)]
		new level = sh_get_user_lvl(player)
		
		if (g_happyhour) {
			
			if ( level <= 15 ) {
				iXPtoAdd = (get_pcvar_num(gPcvarXP)*2)
				}
			else 	{
				iXPtoAdd = (get_pcvar_num(gPcvarXP))
			}
			
			get_user_name(player, name, charsmax(name))
			sh_chat_message(0, -1, "%s Fue El Elegido y recibió %i de XP!", name, iXPtoAdd)
			sh_set_user_xp(player, iXPtoAdd, true)
			}
		else 	{
			
			if ( level <= 15 ) {
				iXPtoAdd = (get_pcvar_num(gPcvarXP))
				}
			else 	{
				iXPtoAdd = ( get_pcvar_num(gPcvarXP)/2 )
			}
			
			get_user_name(player, name, charsmax(name))
			sh_chat_message(0, -1, "%s Fue El Elegido y recibió %i de XP!", name, iXPtoAdd)
			sh_set_user_xp(player, iXPtoAdd, true)
		}
	}
}  
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang11274\\ f0\\ fs16 \n\\ par }
*/
