// Copperhead

/* CVARS - copy and paste to shconfig.cfg

//Copperhead
copper_level 0
copper_none 0.0			//Bet multiplier for getting nothing
copper_two 1.0			//Bet multiplier for getting one pair
copper_double 5.0		//Bet multiplier for getting two pairs
copper_three 6.0		//Bet multiplier for getting 3 of a kind
copper_straight 7.5		//Bet multiplier for getting sequential numbers
copper_four 10.0		//Bet multiplier for getting 4 of a kind
copper_1337 1337		//Bet multiplier for getting 1337

*/

#include <superheromod>
#include <amxmisc>

// Bandera usado para multiplicador de xp y/o Admin
#define DATA_FLAG2 "r"

// GLOBAL VARIABLES
new gHeroID;
new const gHeroName[] = "Copperhead";
new gCopper[SH_MAXSLOTS+1];
new copper_none, copper_two, copper_double, copper_three, copper_straight, copper_four, copper_1337;

new copper_none2, copper_straight2, copper_four2, copper_13372;
new gMsgSync
new bool: g_happyhour
//new const horas[] = { 11,12,13,14,15,16,17,18,19,20,21,22,23,00,01,02,03,04,05,06,07,08,09,10 } // orden real
new const horas[] = { 11,12,13,22,23,00,01,02,03,04,05,06,07,08,09,10 }
//----------------------------------------------------------------------------------------------
public plugin_init()
{
	// Plugin Info
	register_plugin("SUPERHERO Copperhead", SH_VERSION_STR, "Emp`");

	// DO NOT EDIT THIS FILE TO CHANGE CVARS, USE THE SHCONFIG.CFG
	new copper_level = register_cvar("copper_level", "5");
	copper_none = register_cvar("copper_none", "0.50	");	//0.25 es igual a que te quedas con un cuarto de la apuesta.
	copper_two = register_cvar("copper_two", "1.5");   // 1.0 es igual a nada, es la apuesta + la mitad de la misma
	copper_double = register_cvar("copper_double", "3.0");
	copper_three = register_cvar("copper_three", "5.0");		//es la apuesta multiplicada nada mas
	copper_straight = register_cvar("copper_straight", "10.0");    //es la apuesta multiplicada nada mas
	copper_four = register_cvar("copper_four", "15.0");
	copper_1337 = register_cvar("copper_1337", "777");
	
	// Para el multiplicador de Xp
	copper_none2 = register_cvar("copper_none2", "0.75");	//0.25 es igual a que te quedas con un cuarto de la apuesta.
	copper_straight2 = register_cvar("copper_straight2", "12.0");
	copper_four2 = register_cvar("copper_four2", "17.0");
	copper_13372 = register_cvar("copper_13372", "777");

	// FIRE THE EVENTS TO CREATE THIS SUPERHERO!
	gHeroID = sh_create_hero(gHeroName, copper_level);
	sh_set_hero_info(gHeroID, "Apuestas de XP.", "Apuesta la Xp obtenida tras un asesinato con la posibilidad de ganar más o perderla.");
	
	register_event("HLTV", "RoundStart", "a", "1=0", "2=0");
	
	gMsgSync = CreateHudSyncObj()
}
//----------------------------------------------------------------------------------------------
public sh_hero_init(id, heroID, mode)
{
	if( gHeroID != heroID ) return;
	
	gCopper[id] = mode;
}
//----------------------------------------------------------------------------------------------
public sh_client_death(victim, attacker)
{
	new maxplayers = sh_maxplayers();
	if( victim < 1 || victim > maxplayers || attacker < 1 || attacker > maxplayers || victim == attacker ) return;
	if( gCopper[attacker] != 1) return;
	if( g_happyhour ) return;
	
	
	if ( is_user_alive(attacker) && victim != attacker ) 
		{
		if (has_flag(attacker, DATA_FLAG2)) {	
			new killxp = sh_get_user_xp(attacker);
			sh_add_kill_xp(attacker, victim, -1.0)
			killxp -= sh_get_user_xp(attacker);
			
			gCopper[attacker] = 2;
			sh_chat_message( attacker, gHeroID, "Estás apostando %d de puntos de experiencia.", killxp );

			new parm[3];
			parm[0] = attacker;
			parm[1] = killxp;
			parm[2] = 30;
			Gamble2 (parm);
			}
		
	
		else 	{
			new killxp = sh_get_user_xp( attacker );
			sh_add_kill_xp( attacker, victim, -1.0 );
			killxp -= sh_get_user_xp( attacker );
	
			gCopper[attacker] = 2;
			sh_chat_message( attacker, gHeroID, "Estás apostando %d de puntos de experiencia.", killxp );

			new parm[3];
			parm[0] = attacker;
			parm[1] = killxp;
			parm[2] = 30;
			Gamble (parm);
			}
		}
}
//----------------------------------------------------------------------------------------------
public Gamble( parm[] )
{
	set_hudmessage(114, 114, 114, -1.0, 0.40, 1, 0.02, 0.1, 0.0, 0.0, 1)
	//set_hudmessage(50, 205, 50, -1.0, 0.40, 2, 0.02, 4.0, 0.01, 0.1, 7)	// Es el original
	ShowSyncHudMsg(parm[0], gMsgSync, "[%d][%d][%d][%d]", random(7)+1, random(7)+1, random(7)+1, random(7)+1 )
	
	parm[2]--;
	if( !parm[2] ) Gamble_Finish( parm );
	else set_task( 0.1, "Gamble", 0, parm, 3 );
}
//----------------------------------------------------------------------------------------------
Gamble_Finish( parm[] )
{
	new dice[4];
	for( new i=0; i<4; i++ )
		dice[i] = random(7) + 1;

	SortIntegers(dice, 4, Sort_Ascending);	
	
	set_hudmessage(255, 255, 255, -1.0, 0.40, 2, 0.02, 0.7, 0.0, 0.0, 1)
	//set_hudmessage(50, 205, 50, -1.0, 0.40, 2, 0.02, 4.0, 0.01, 0.1, 7);	// es el original
	ShowSyncHudMsg(parm[0], gMsgSync, "[%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3])

	new Float:xp_multiplier;

	if( dice[0] == dice[3] ){
		xp_multiplier = get_pcvar_float( copper_four );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 4 dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[2] || dice[1] == dice[3] ){
		xp_multiplier = get_pcvar_float( copper_three );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 3 dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[1] && dice[2] == dice[3] ){
		xp_multiplier = get_pcvar_float( copper_double );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 2 pares de dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == 1 && dice[1] == 3 && dice[2] == 3 && dice[3] == 7 ){
		xp_multiplier = get_pcvar_float( copper_1337 );
		sh_chat_message( parm[0], gHeroID, "Conseguiste el 1337!!! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[1] || dice[1] == dice[2] || dice[2] == dice[3] ){
		xp_multiplier = get_pcvar_float( copper_two );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 1 par de dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[1]-1 && dice[1] == dice[2]-1 && dice[2] == dice[3]-1 ){
		xp_multiplier = get_pcvar_float( copper_straight );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 1 escalera! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else{
		xp_multiplier = get_pcvar_float( copper_none );
		sh_chat_message( parm[0], gHeroID, "No conseguiste nada. [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}

	new xp_outcome = floatround( parm[1] * xp_multiplier );

	if( xp_outcome ){
		sh_set_user_xp( parm[0], xp_outcome, true );

		if( xp_outcome > parm[1] ) sh_chat_message( parm[0], gHeroID, "Ganaste un adicional de %d Puntos de Experiencia!", xp_outcome - parm[1] );
		else if( xp_outcome < 0 ) sh_chat_message( parm[0], gHeroID, "You lost your %d bet and an additional %d experience points.", parm[1], abs( xp_outcome ) );
		else sh_chat_message( parm[0], gHeroID, "Perdiste %d de Puntos de Experiencia de tu apuesta de %d.", parm[1] - xp_outcome, parm[1] );
	}
	else sh_chat_message( parm[0], gHeroID, "Perdiste toda tu apuesta de %d.", parm[1] );

	gCopper[ parm[0] ] = 1;
}
//----------------------------------------------------------------------------------------------
public client_connect(id)
	gCopper[id] = 0;

//----------------------------------------------------------------------------------------------
public RoundStart()
{
	new data[12] 
	get_time("%H", data, 12) 
	new Tiempo = str_to_num(data) 
    
	for(new i=0;i <= sizeof horas - 1;i++) { 
		if(Tiempo != horas[i]) continue 
		g_happyhour = true 
		break; 
		}
}


public sh_client_spawn(id)
{
	if ( gCopper[id] && is_user_alive(id) ) {
	
		new level = sh_get_user_lvl(id)
		if ( g_happyhour && level > 20 )
			sh_chat_message(id, gHeroID, "Hay HappyHour Sacate el %s, Ya que no funcionará durante el evento.", gHeroName)	
	}
}
//----------------------------------------------------------------------------------------------
public Gamble2( parm[] )
{
	set_hudmessage(114, 114, 114, -1.0, 0.40, 1, 0.02, 0.1, 0.0, 0.0, 1)
	ShowSyncHudMsg(parm[0], gMsgSync, "[%d][%d][%d][%d]", random(7)+1, random(7)+1, random(7)+1, random(7)+1 )
	// show_hudmessage(parm[0], "[%d][%d][%d][%d]", random(7)+1, random(7)+1, random(7)+1, random(7)+1 )
	
	parm[2]--;
	if( !parm[2] ) Gamble_Finish2( parm );
	else set_task( 0.1, "Gamble2", 0, parm, 3 );
}
//----------------------------------------------------------------------------------------------
Gamble_Finish2( parm[] )
{
	new dice[4];
	for( new i=0; i<4; i++ )
		dice[i] = random(7) + 1;

	SortIntegers(dice, 4, Sort_Ascending);	
	set_hudmessage(255, 255, 255, -1.0, 0.40, 2, 0.02, 0.7, 0.0, 0.0, 1)
	ShowSyncHudMsg(parm[0], gMsgSync, "[%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3]) 
	// show_hudmessage(parm[0], "[%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3])
	
	new Float:xp_multiplier2;

	if( dice[0] == dice[3] ){
		xp_multiplier2 = get_pcvar_float( copper_four2 );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 4 dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[2] || dice[1] == dice[3] ){
		xp_multiplier2 = get_pcvar_float( copper_three );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 3 dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[1] && dice[2] == dice[3] ){
		xp_multiplier2 = get_pcvar_float( copper_double );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 2 pares de dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == 1 && dice[1] == 3 && dice[2] == 3 && dice[3] == 7 ){
		xp_multiplier2 = get_pcvar_float( copper_13372 );
		sh_chat_message( parm[0], gHeroID, "Conseguiste el 1337!!! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[1] || dice[1] == dice[2] || dice[2] == dice[3] ){
		xp_multiplier2 = get_pcvar_float( copper_two );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 1 par de dados iguales! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else if( dice[0] == dice[1]-1 && dice[1] == dice[2]-1 && dice[2] == dice[3]-1 ){
		xp_multiplier2 = get_pcvar_float( copper_straight2 );
		sh_chat_message( parm[0], gHeroID, "Conseguiste 1 escalera! [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}
	else{
		xp_multiplier2 = get_pcvar_float( copper_none2 );
		sh_chat_message( parm[0], gHeroID, "No conseguiste nada. [%d][%d][%d][%d]", dice[0], dice[1], dice[2], dice[3] );
	}

	new xp_outcome2 = floatround( parm[1] * xp_multiplier2 );

	if( xp_outcome2 ){
		sh_set_user_xp( parm[0], xp_outcome2, true );

		if( xp_outcome2 > parm[1] ) sh_chat_message( parm[0], gHeroID, "Ganaste un adicional de %d Puntos de Experiencia!", xp_outcome2 - parm[1] );
		else if( xp_outcome2 < 0 ) sh_chat_message( parm[0], gHeroID, "You lost your %d bet and an additional %d experience points.", parm[1], abs( xp_outcome2 ) );
		else sh_chat_message( parm[0], gHeroID, "Perdiste %d de Puntos de Experiencia de tu apuesta de %d.", parm[1] - xp_outcome2, parm[1] );
	}
	else sh_chat_message( parm[0], gHeroID, "Perdiste toda tu apuesta de %d.", parm[1] );

	gCopper[ parm[0] ] = 1;
}
//---------------------------------------------------------------------------------------------
/* AMXX-Studio Notes - DO NOT MODIFY BELOW HERE
*{\\ rtf1\\ ansi\\ deff0{\\ fonttbl{\\ f0\\ fnil Tahoma;}}\n\\ viewkind4\\ uc1\\ pard\\ lang11274\\ f0\\ fs16 \n\\ par }
*/
